SET SERVEROUTPUT ON;

CREATE OR REPLACE FUNCTION FN_INF_PRODUCT_ORDER( ID_ORDER NUMBER )
RETURN SYS_REFCURSOR
IS
    CDATOS SYS_REFCURSOR;
BEGIN
    OPEN CDATOS FOR 
    SELECT 
        DEMO_ORDERS.ORDER_ID, 
        DEMO_PRODUCT_INFO.PRODUCT_ID,
        DEMO_PRODUCT_INFO.PRODUCT_NAME,
        DEMO_ORDERS.ORDER_TOTAL, 
        DEMO_ORDERS.ORDER_TIMESTAMP 
    FROM DEMO_ORDERS
    RIGHT JOIN DEMO_ORDER_ITEMS 
    ON DEMO_ORDERS.ORDER_ID = DEMO_ORDER_ITEMS.ORDER_ID
    INNER JOIN DEMO_PRODUCT_INFO 
    ON DEMO_ORDER_ITEMS.PRODUCT_ID = DEMO_PRODUCT_INFO.PRODUCT_ID
    WHERE DEMO_ORDERS.ORDER_ID = ID_ORDER;

    RETURN CDATOS;
END;
/