SET SERVEROUTPUT ON;

CREATE OR REPLACE PROCEDURE SP_ACTUALIZAR_QUOTA(
    NEW_QUOTA IN NUMBER,
    MSJ OUT NUMBER
)
IS
BEGIN
    UPDATE DEMO_USERS SET QUOTA = NEW_QUOTA WHERE QUOTA IS NULL;
    COMMIT;
    MSJ:=1;

    EXCEPTION
        WHEN OTHERS THEN
        ROLLBACK;
        MSJ:=2;
END;
/

DECLARE
    MSJ NUMBER;
BEGIN
    SP_ACTUALIZAR_QUOTA(300, MSJ);
    IF (MSJ = 1) THEN
        DBMS_OUTPUT.PUT_LINE('LA COLUMNA QUOTA FUE ACTUALIZADA');
    ELSIF (MSJ = 2) THEN
        DBMS_OUTPUT.PUT_LINE('SURGIO UN ERROR CUANDO SE INTENTO ACTUALIZAR LA COLUMNA ');
    END IF;
END;
/

 --UPDATE DEMO_USERS SET QUOTA = NULL WHERE USER_ID=1;
 --COMMIT;