SET SERVEROUTPUT ON;

CREATE OR REPLACE PROCEDURE SP_INSERTAR_EMPLEADO(
    EMPLOYEE_ID EMPLOYEES.EMPLOYEE_ID%TYPE,
    FIRST_NAME EMPLOYEES.FIRST_NAME%TYPE,
    LAST_NAME EMPLOYEES.LAST_NAME%TYPE,
    EMAIL EMPLOYEES.EMAIL%TYPE,
    PHONE_NUMBER EMPLOYEES.PHONE_NUMBER%TYPE, 
    HIRE_DATE EMPLOYEES.HIRE_DATE%TYPE, 
    JOB_ID EMPLOYEES.JOB_ID%TYPE, 
    SALARY EMPLOYEES.SALARY%TYPE, 
    COMMISSION_PCT EMPLOYEES.COMMISSION_PCT%TYPE, 
    MANAGER_ID EMPLOYEES.MANAGER_ID%TYPE, 
    DEPARTMENT_ID EMPLOYEES.DEPARTMENT_ID%TYPE,
    MSJ OUT NUMBER
)
IS
BEGIN

    INSERT INTO EMPLOYEES VALUES (
        EMPLOYEE_ID,
        FIRST_NAME,
        LAST_NAME,
        EMAIL,
        PHONE_NUMBER,
        HIRE_DATE,
        JOB_ID,
        SALARY,
        COMMISSION_PCT,
        MANAGER_ID,
        DEPARTMENT_ID
    );
    COMMIT;
    MSJ:=1;

    EXCEPTION
        WHEN OTHERS THEN
        ROLLBACK;
        MSJ:=2;
END;
/

DECLARE
    MSJ NUMBER;
BEGIN
    SP_INSERTAR_EMPLEADO(66, 'SUE', 'JINEZ', 'menez.josue@gmail.com', '88298881', SYSDATE , 'ST_CLERK', 24000, NULL, 100, 90, MSJ);
    IF (MSJ = 1) THEN
        DBMS_OUTPUT.PUT_LINE('EL EMPLEADO FUE INSERTADO');
    ELSIF (MSJ = 2) THEN
        DBMS_OUTPUT.PUT_LINE('SURGIO UN ERROR CUANDO SE INTENTO INSERTAR EL EMPLEADO ');
    END IF;
END;
/