SET SERVEROUTPUT ON;

CREATE OR REPLACE PACKAGE PK_INF_EMPRESA
IS
    PROCEDURE SP_INSERT_LOCATION_COUNTRY (
        LOCATION_ID LOCATIONS.LOCATION_ID%TYPE,
        STREET_ADDRESS LOCATIONS.STREET_ADDRESS%TYPE,
        POSTAL_CODE LOCATIONS.POSTAL_CODE%TYPE,
        CITY LOCATIONS.CITY%TYPE,
        STATE_PROVINCE LOCATIONS.STATE_PROVINCE%TYPE,
        COUNTRY_ID COUNTRIES.COUNTRY_ID%TYPE,
        COUNTRY_NAME COUNTRIES.COUNTRY_NAME%TYPE,
        REGION_ID COUNTRIES.REGION_ID%TYPE,
        MSJ OUT NUMBER
    );
    
    FUNCTION FN_TOTAL_EMPLEADOS RETURN VARCHAR2;
END;
/

CREATE OR REPLACE PACKAGE BODY PK_INF_EMPRESA
IS
    PROCEDURE SP_INSERT_LOCATION_COUNTRY (
        LOCATION_ID LOCATIONS.LOCATION_ID%TYPE,
        STREET_ADDRESS LOCATIONS.STREET_ADDRESS%TYPE,
        POSTAL_CODE LOCATIONS.POSTAL_CODE%TYPE,
        CITY LOCATIONS.CITY%TYPE,
        STATE_PROVINCE LOCATIONS.STATE_PROVINCE%TYPE,
        COUNTRY_ID COUNTRIES.COUNTRY_ID%TYPE,
        COUNTRY_NAME COUNTRIES.COUNTRY_NAME%TYPE,
        REGION_ID COUNTRIES.REGION_ID%TYPE,
        MSJ OUT NUMBER
    )
    IS
    BEGIN
        INSERT INTO COUNTRIES VALUES (
            COUNTRY_ID,
            COUNTRY_NAME,
            REGION_ID
        );

        INSERT INTO LOCATIONS VALUES(
            LOCATION_ID,
            STREET_ADDRESS,
            POSTAL_CODE,
            CITY,
            STATE_PROVINCE,
            COUNTRY_ID
        );

        COMMIT;
       
        MSJ:=1;

        EXCEPTION
            WHEN OTHERS THEN
            ROLLBACK;
            MSJ:=2;
    END;


    FUNCTION FN_TOTAL_EMPLEADOS
    RETURN VARCHAR2
    IS
        CANTIDAD NUMBER;
        MSJ_CANTIDAD VARCHAR2(100);
    BEGIN 
      
        SELECT COUNT(EMPLOYEE_ID) INTO CANTIDAD
        FROM EMPLOYEES
        WHERE SALARY BETWEEN 9000 AND 20000;

        MSJ_CANTIDAD := 'La cantidad de empleados con un salario entre 9000 y 20000 es: ' || CANTIDAD;
      
        RETURN MSJ_CANTIDAD;
    END;
    
END;
/

--EJECUCCION
DECLARE 
    MSJ_CANTIDAD VARCHAR(100);
    MSJ NUMBER;
BEGIN
    MSJ_CANTIDAD := PK_INF_EMPRESA.FN_TOTAL_EMPLEADOS();
    DBMS_OUTPUT.PUT_LINE(' ');
    DBMS_OUTPUT.PUT_LINE('PRUEBA FUNCION');
    DBMS_OUTPUT.PUT_LINE(MSJ_CANTIDAD);
    
    PK_INF_EMPRESA.SP_INSERT_LOCATION_COUNTRY(
      1,
      'BOULEVARD SUYAPA',
      11101,
      'TEGUCIGALPA',
      'DC',
      'HN',
      'HONDURAS',
      2,
      MSJ
    );
    DBMS_OUTPUT.PUT_LINE(' ');
    DBMS_OUTPUT.PUT_LINE('PRUEBA PROCEDIMIENTO ALMACENADO');
    IF (MSJ = 1) THEN
        DBMS_OUTPUT.PUT_LINE('EL LUGAR FUE INSERTADO');
    ELSIF (MSJ = 2) THEN
        DBMS_OUTPUT.PUT_LINE('SURGIO UN ERROR CUANDO SE INTENTO INSERTAR EL LUGAR');
    END IF;

END;
/