SET SERVEROUTPUT ON;

CREATE OR REPLACE PROCEDURE SP_OBTENER_INF_PRODUCT_ORDER ( 
    ID_ORDER NUMBER 
)
IS
    DATOS_CAT SYS_REFCURSOR;
    ORDER_ID  DEMO_ORDERS.ORDER_ID%TYPE ;
    PRODUCT_ID DEMO_PRODUCT_INFO.PRODUCT_ID%TYPE;
    PRODUCT_NAME DEMO_PRODUCT_INFO.PRODUCT_NAME%TYPE;
    ORDER_TOTAL  DEMO_ORDERS.ORDER_TOTAL%TYPE;
    ORDER_TIMESTAMP DEMO_ORDERS.ORDER_TIMESTAMP%TYPE; 
BEGIN
   DATOS_CAT := FN_INF_PRODUCT_ORDER(ID_ORDER);

    LOOP
        FETCH DATOS_CAT 
        INTO 
            ORDER_ID,
            PRODUCT_ID,
            PRODUCT_NAME,
            ORDER_TOTAL,
            ORDER_TIMESTAMP
        ;

        EXIT WHEN DATOS_CAT%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE(' ');
        DBMS_OUTPUT.PUT_LINE('EL ID DE LA ORDEN ES: ' || ORDER_ID);
        DBMS_OUTPUT.PUT_LINE('EL ID DEL PRODUCTO ES: ' || PRODUCT_ID);
        DBMS_OUTPUT.PUT_LINE('EL NOMBRE DEL PRODUCTO ES: ' || PRODUCT_NAME);
        DBMS_OUTPUT.PUT_LINE('EL TORAL PAGADO DE LA ORDEN ES: ' || ORDER_TOTAL);
        DBMS_OUTPUT.PUT_LINE('LA FECHA DE LA ORDEN ES: ' || ORDER_TIMESTAMP);
       
    END LOOP;
END;
/

---EJECUCION 
DECLARE
BEGIN
  SP_OBTENER_INF_PRODUCT_ORDER(2);
END;
/