SET SERVEROUTPUT ON;

CREATE OR REPLACE PROCEDURE SP_OBTENER_INF_MAX_SALARY 
IS
    DATOS_CAT SYS_REFCURSOR;
    FULL_NAME VARCHAR2(46);
    EMPLOYEE_ID EMPLOYEES.EMPLOYEE_ID%TYPE;
    SALARY EMPLOYEES.SALARY%TYPE;
    DEPARTMENT_ID EMPLOYEES.DEPARTMENT_ID%TYPE;
BEGIN
   DATOS_CAT := FN_INF_MAX_SALARY();

    LOOP
        FETCH DATOS_CAT 
        INTO 
            FULL_NAME,
            EMPLOYEE_ID,
            SALARY,
            DEPARTMENT_ID
        ;

        EXIT WHEN DATOS_CAT%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE(' ');
        DBMS_OUTPUT.PUT_LINE('EL NOMBRE COMPLETO DEL EMPLEADO ES: ' || FULL_NAME);
        DBMS_OUTPUT.PUT_LINE('EL ID DEL EMPLEADO ES: ' || EMPLOYEE_ID);
        DBMS_OUTPUT.PUT_LINE('EL SALARIO DEL EMPLEADO ES: ' || SALARY);
        DBMS_OUTPUT.PUT_LINE('EL ID DEL DEPARTAMENTO DONDE TRABAJA ES: ' || DEPARTMENT_ID);
        
       
    END LOOP;
END;
/

EXECUTE SP_OBTENER_INF_MAX_SALARY();