CREATE USER BD_BICICLETAS IDENTIFIED BY 123
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp
QUOTA UNLIMITED ON users;

CREATE ROLE ADMINISTRADORES;

GRANT CREATE SESSION, CREATE ANY TABLE , CREATE ANY PROCEDURE, ALTER ANY TABLE,
ALTER ANY PROCEDURE, DROP ANY TABLE, DROP ANY PROCEDURE TO ADMINISTRADORES;

GRANT ADMINISTRADORES TO BD_BICICLETAS

---CONSULTA PARA VERIFICAR LOS ROLES CREADOS 
SELECT * FROM DBA_ROLES;

---CONSULTA PARA VERIFICAR LOS PRIVILEGIOS ASIGNAODS A UN ROL
SELECT * FROM DBA_SYS_PRIVS WHERE GRANTEE='ADMINISTRADORES';