SET SERVEROUTPUT ON;

---------------------IF/ELSE STATEMENT--------------------------

DECLARE 
  RESULTADO NUMBER (10,2);
  PARAMETRO NUMBER(1) := 2;
  PORCENTAJE NUMBER;
  SALARIO NUMBER(10,2) := 12000;
BEGIN 
    DBMS_OUTPUT.PUT_LINE('El aumento para un empleado es: ');
    IF( PARAMETRO = 1 ) THEN
      PORCENTAJE := 0.05;
      RESULTADO := PORCENTAJE*SALARIO;
    ELSIF (PARAMETRO=2) THEN
      PORCENTAJE := 0.15;
      RESULTADO := PORCENTAJE*SALARIO;
    ELSE
      DBMS_OUTPUT.PUT_LINE('NO SE PUEDE CALCULAR EL AUMENTO CON LOS DATOS PROPORCIONADOS');
    END IF;
    
    DBMS_OUTPUT.PUT_LINE(RESULTADO);
END;

---------------------SWITCH STATEMENT--------------------------

DECLARE 
  RESULTADO NUMBER (10,2);
  PARAMETRO NUMBER(1) := 2;
  PORCENTAJE NUMBER;
  SALARIO NUMBER(10,2) := 12000;
BEGIN 
    DBMS_OUTPUT.PUT_LINE('El aumento para un empleado es: ');
    CASE
      WHEN( PARAMETRO = 1 ) THEN
        PORCENTAJE := 0.05;
        RESULTADO := PORCENTAJE*SALARIO;
      WHEN (PARAMETRO=2) THEN
        PORCENTAJE := 0.15;
        RESULTADO := PORCENTAJE*SALARIO;
      ELSE      
        DBMS_OUTPUT.PUT_LINE('NO SE PUEDE CALCULAR EL AUMENTO CON LOS DATOS PROPORCIONADOS');
    END CASE;
    
    DBMS_OUTPUT.PUT_LINE(RESULTADO);
END;
