GRANT SELECT ON BD_CENSO.TBLPAISES TO ADMINISTRADORES;

GRANT INSERT, UPDATE, DELETE ON BD_CENSO.TBLPAISES TO ADMINISTRADORES;

SELECT * FROM DBA_SYS_PRIVS WHERE GRANTEE='ADMINISTRADORES';

--- VER LOS PRIVILEGIOS EN OTRAS TABLAS
SELECT * FROM DBA_TAB_PRIVS WHERE GRANTEE='ADMINISTRADORES';


--- REMOVER PRIVILEGIOS DE UN ROL 
REVOKE CREATE ANY PROCEDURE, DROP ANY PROCEDURE, ALTER ANY PROCEDURE FROM 
ADMINISTRADORES;

REVOKE SELECT ON BD_CENSO.PAISES FROM ADMINISTRADORES;


------------------------ANONYMOUS BLOCK--------------------------

DECLARE 
  nombre_completo VARCHAR2(100) := 'Gabriel Escobar' ;
BEGIN 
  DBMS_OUTPUT.PUT_LINE('El nombre de la persona es: ' ||nombre_completo);
END;

SET SERVEROUTPUT ON;




