SET SERVEROUTPUT ON;

---------------------- SIMPLE LOOP -------------------------

DECLARE 
  ITERACION   NUMBER(3) := 0;
  FECHA DATE;
BEGIN 
  LOOP
    FECHA := SYSDATE+ITERACION;
    EXIT WHEN ITERACION>3;
    DBMS_OUTPUT.PUT_LINE('Ciclo ' || ITERACION);
    DBMS_OUTPUT.PUT_LINE(FECHA);
    ITERACION := ITERACION + 1 ;
  END LOOP;
END;


--------------------- WHILE LOOP --------------------------
SET SERVEROUTPUT ON;

DECLARE 
  ITERACION   NUMBER(3) := 0;
  FECHA DATE;
BEGIN 
  WHILE (ITERACION<=3) LOOP
    FECHA := SYSDATE+ITERACION;
    DBMS_OUTPUT.PUT_LINE('Ciclo ' || ITERACION);
    DBMS_OUTPUT.PUT_LINE(FECHA);
    ITERACION := ITERACION + 1 ;
  END LOOP;
END;

---------------------- FOR LOOP (CONSTANT RANGE) -------------------------
SET SERVEROUTPUT ON;

DECLARE 
  ITERACION   NUMBER(3) := 0;
  FECHA DATE;
BEGIN 
  FOR ITERACION IN 0..5 LOOP
    FECHA := SYSDATE+ITERACION;
    DBMS_OUTPUT.PUT_LINE('Ciclo ' || ITERACION);
    DBMS_OUTPUT.PUT_LINE(FECHA);
  END LOOP;
END;

----------------------- FOR LOOP (VARIABLE RANGE) -----------------------

SET SERVEROUTPUT ON;

DECLARE 
  ITERACION   NUMBER(3) := 0;
  VALOR_INICIAL NUMBER(3) := 0;
  VALOR_FINAL NUMBER(3) := 6;
  FECHA DATE;
  
BEGIN 
  FOR ITERACION IN VALOR_INICIAL..VALOR_FINAL  LOOP
    FECHA := SYSDATE+ITERACION;
    DBMS_OUTPUT.PUT_LINE('Ciclo ' || ITERACION);
    DBMS_OUTPUT.PUT_LINE(FECHA);
  END LOOP;
END;

