CREATE USER GABRIEL IDENTIFIED BY 123
DEFAUL TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON USERS;


GRANT ALL PRIVILEGES TO GABRIEL;

-- PARA QUE FUNCIONE SE NECESITA QUE TODOS LOS PRIVILEGIOS ESTEN CONCEDIDOS
REVOKE ALL PRIVILEGES FROM GABRIEL;