
---PRIVILEGIOS
GRANT CREATE ANY JOB TO ADMINISTRADORES;


--CREACION DE PROCEDIMIENTO ALMACENADO O FUNCION QUE USARA EL JOB
CREATE OR REPLACE PROCEDURE SP_NOMB_BRAND_MAYUS
IS
BEGIN
    UPDATE BRANDS SET BRAND_NAME = UPPER(BRAND_NAME);
    COMMIT;
END;


--CREACION DEL JOB
BEGIN
DBMS_SCHEDULER.CREATE_JOB(
    JOB_NAME => 'JOB_MAYUS_BRAND_NAME',
    JOB_TYPE => 'STORED_PROCEDURE',
    JOB_ACTION => 'SP_NOMB_BRAND_MAYUS',
    NUMBER_OF_ARGUMENTS => 0,
    START_DATE => TO_TIMESTAMP('2020-03-31 11:21:00', 'YYYY-MM-DD HH24:MI:SS' ),
    REPEAT_INTERVAL => 'FREQ=DAILY',
    ENABLED => TRUE
);
END;

--RETORNAR LOS JOBS QUE SE HAN CREADO
SELECT * FROM USER_SCHEDULER_JOBS;

--CONSULTA PARA VER LOS JOBS QUE SE HAN EJECUTADO Y SI ESTOS HAN TENIDO EXITO EN SU EJECUCION
SELECT JOB_NAME, LOG_DATE, STATUS FROM USER_SCHEDULER_JOB_LOG;

BEGIN
    --EJECUTAR EL JOB DE FORMA MANUAL
    DBMS_SCHEDULER.RUN_JOB(
        JOB_NAME => 'JOB_MAYUS_BRAND_NAME'
    );

    --ELIMINAR EL JOB DE FORMA MANUAL
    DBMS_SCHEDULER.DROP_JOB(
        JOB_NAME => 'JOB_MAYUS_BRAND_NAME'
    );
END;