-- EJECUCION DE LA CLASE ANTERIOR 
DECLARE
    DATOS_CAT SYS_REFCURSOR;

    TYPE FILA IS RECORD(
        ORDER_ID ORDERS.ORDER_ID%TYPE,
        ORDER_DATE ORDERS.ORDER_DATE%TYPE,
        SHIPPED_DATE ORDERS.SHIPPED_DATE%TYPE,
        CUSTOMER_ID CUSTOMERS.CUSTOMER_ID%TYPE,
        FIRST_NAME CUSTOMERS.FIRST_NAME%TYPE,
        LAST_NAME CUSTOMERS.LAST_NAME%TYPE
    );

    REGISTRO FILA;

    
BEGIN
    DATOS_CAT := FN_INF_ORDER_CLIENTES;

    LOOP
        FETCH DATOS_CAT INTO REGISTRO;

        EXIT WHEN DATOS_CAT%NOTFOUND;

        
        DBMS_OUTPUT.PUT_LINE(' ');
        DBMS_OUTPUT.PUT_LINE('EL ORDER_ID DE LA ORDEN ES: ' || REGISTRO.ORDER_ID);
        DBMS_OUTPUT.PUT_LINE('EL ORDER_DATE DE LA ORDEN ES: ' || REGISTRO.ORDER_DATE);
        DBMS_OUTPUT.PUT_LINE('EL SHIPPED_DATE DE LA ORDEN ES: ' || REGISTRO.SHIPPED_DATE);
        DBMS_OUTPUT.PUT_LINE('EL CUSTOMER_ID DE LA CLIENTE ES: ' || REGISTRO.CUSTOMER_ID);
        DBMS_OUTPUT.PUT_LINE('EL FIRST_NAME DE LA CLIENTE ES: ' || REGISTRO.FIRST_NAME);
        DBMS_OUTPUT.PUT_LINE('EL LAST_NAME DE LA CLIENTE ES: ' || REGISTRO.LAST_NAME);
    END LOOP;
END;