--- Funcion que retorna varios registros ---
CREATE OR REPLACE FUNCTION FN_INF_CATEGORIAS
RETURN SYS_REFCURSOR
IS
    CDATOS SYS_REFCURSOR;
BEGIN
    OPEN CDATOS FOR 
    SELECT CATEGORY_ID, CATEGORY_NAME 
    FROM CATEGORIES;

    RETURN CDATOS;
END;

-- EJECUCION
DECLARE
    DATOS_CAT SYS_REFCURSOR;
    REGISTRO CATEGORIES%ROWTYPE;
BEGIN
    DATOS_CAT := FN_INF_CATEGORIAS;

    LOOP
        FETCH DATOS_CAT INTO REGISTRO;
        EXIT WHEN DATOS_CAT%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE(' ');
        DBMS_OUTPUT.PUT_LINE('EL ID DE LA CATEGORIA ES: ' || REGISTRO.CATEGORY_ID);
        DBMS_OUTPUT.PUT_LINE('EL NOMBRE DE LA CATEGORIA ES: ' || REGISTRO.CATEGORY_NAME);
    END LOOP;
END;


--- Funcion que retorna varios registros de diferentes tablas ---
CREATE OR REPLACE FUNCTION FN_INF_ORDER_CLIENTES
RETURN SYS_REFCURSOR
IS
    CDATOS SYS_REFCURSOR;
BEGIN
    OPEN CDATOS FOR 
    SELECT 
        ORDERS.ORDER_ID, 
        ORDERS.ORDER_DATE, 
        ORDERS.SHIPPED_DATE,
        CUSTOMERS.CUSTOMER_ID,
        CUSTOMERS.FIRST_NAME,
        CUSTOMERS.LAST_NAME
    FROM ORDERS
    INNER JOIN CUSTOMERS 
    ON ORDERS.CUSTOMER_ID = CUSTOMERS.CUSTOMER_ID;

    RETURN CDATOS;
END;

-- EJECUCION
DECLARE
    DATOS_CAT SYS_REFCURSOR;
    ORDER_ID ORDERS.ORDER_ID%TYPE; 
    ORDER_DATE ORDERS.ORDER_DATE%TYPE; 
    SHIPPED_DATE ORDERS.SHIPPED_DATE%TYPE;
    CUSTOMER_ID CUSTOMERS.CUSTOMER_ID%TYPE;
    FIRST_NAME CUSTOMERS.FIRST_NAME%TYPE;
    LAST_NAME CUSTOMERS.LAST_NAME%TYPE;    
BEGIN
    DATOS_CAT := FN_INF_ORDER_CLIENTES;

    LOOP
        FETCH DATOS_CAT 
        INTO 
            ORDER_ID,
            ORDER_DATE,
            SHIPPED_DATE,
            CUSTOMER_ID,
            FIRST_NAME,
            LAST_NAME
        ;

        EXIT WHEN DATOS_CAT%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE(' ');
        DBMS_OUTPUT.PUT_LINE('EL ORDER_ID DE LA ORDEN ES: ' || ORDER_ID);
        DBMS_OUTPUT.PUT_LINE('EL ORDER_DATE DE LA ORDEN ES: ' || ORDER_DATE);
        DBMS_OUTPUT.PUT_LINE('EL SHIPPED_DATE DE LA ORDEN ES: ' || SHIPPED_DATE);
        DBMS_OUTPUT.PUT_LINE('EL CUSTOMER_ID DE LA CLIENTE ES: ' || CUSTOMER_ID);
        DBMS_OUTPUT.PUT_LINE('EL FIRST_NAME DE LA CLIENTE ES: ' || FIRST_NAME);
        DBMS_OUTPUT.PUT_LINE('EL LAST_NAME DE LA CLIENTE ES: ' || LAST_NAME);
    END LOOP;
END;
