---SINTAXIS DECLARACION DE FUNCION---
--? CREATE OR REPLACE FUNCTION <NOMBRE DE FUNCION> (<PARAMETROS>)
--? RETURN <TIPO DE DATO> 
--? IS 
--?     <DECLARACION DE VARIABLE>
--? BEGIN
--?     <CUERPO DE LA FUNCION>
--? 
--?     RETURN <VALOR A RETORNAR>
--? 
--?     <BLOQUE DE EXCEPCIONES>
--? END;

---CREACION DE FUNCION---
CREATE OR REPLACE FUNCTION FN_CANTIDAD_PRODUCTOS
RETURN NUMBER
IS
    CANTIDAD_PRODUCTOS NUMBER;
BEGIN
    SELECT COUNT(*) INTO CANTIDAD_PRODUCTOS FROM PRODUCTS;

    RETURN CANTIDAD_PRODUCTOS;
END;

--- EJECUTAR FUNCION ---
SELECT FN_CANTIDAD_PRODUCTOS FROM DUAL;


DECLARE
    TOTAL_PRODUCTOS NUMBER;
BEGIN
TOTAL_PRODUCTOS := FN_CANTIDAD_PRODUCTOS;
    DBMS_OUTPUT.PUT_LINE('LA CANTIDAD DE PRODUCTOS ES: ' || TOTAL_PRODUCTOS);
END;


---FUNCION CON PARAMETROS---

CREATE OR REPLACE FUNCTION FN_NOMBRE_CATEGORIA(ID_CAT NUMBER)
RETURN VARCHAR2
IS
    NOMBRE_CATEGORIA CATEGORIES.CATEGORY_NAME%TYPE;
BEGIN
    SELECT CATEGORY_NAME INTO NOMBRE_CATEGORIA
    FROM CATEGORIES
    WHERE CATEGORY_ID=ID_CAT;

    RETURN NOMBRE_CATEGORIA;
END;

--EJECUCION
DECLARE
    NOMBRE CATEGORIES.CATEGORY_NAME%TYPE;
BEGIN 
    NOMBRE := FN_NOMBRE_CATEGORIA(4);
    DBMS_OUTPUT.PUT_LINE('EL NOMBRE DE LA CATEGORIA ES: ' || NOMBRE);
END;

---FUNCION CON PARAMETROS V2---
CREATE OR REPLACE FUNCTION FN_NOMBRE_CATEGORIA(
    ID_CAT NUMBER,
    NOMB_CAT OUT VARCHAR2
)
RETURN VARCHAR2
IS
    NOMBRE_CATEGORIA CATEGORIES.CATEGORY_NAME%TYPE;
BEGIN
    SELECT CATEGORY_NAME INTO NOMBRE_CATEGORIA
    FROM CATEGORIES
    WHERE CATEGORY_ID=ID_CAT;

    NOMB_CAT := NOMBRE_CATEGORIA;

    RETURN NOMBRE_CATEGORIA;
END;

-- EJECUCION V2
DECLARE
    NOMBRE_FUNCION CATEGORIES.CATEGORY_NAME%TYPE;
    NOMBRE_PARAMETRO CATEGORIES.CATEGORY_NAME%TYPE;
BEGIN 
    NOMBRE_FUNCION := FN_NOMBRE_CATEGORIA(4, NOMBRE_PARAMETRO);
    DBMS_OUTPUT.PUT_LINE('EL NOMBRE DE LA CATEGORIA QUE RETORNA LA FUNCION ES: ' || NOMBRE_FUNCION);
    DBMS_OUTPUT.PUT_LINE('EL NOMBRE DE LA CATEGORIA QUE RETORNA EL PARAMETRO ES: ' || NOMBRE_PARAMETRO);
END;