---CREAR UNA FUNCION QUE OBTENGA LOS CAMPOS NOMBRE DE TIENDA, TELEFONO, CORREO Y CALLE DE LA TABLA SOTRES, Y ESTO SE RETORNARA EN BASE AL ID DE LA TIENDA.

CREATE OR REPLACE FUNCTION FN_DATOS_TIENDA(
    ID_TIENDA STORES.STORE_ID%TYPE,
    TELEFONO OUT STORES.PHONE%TYPE,
    CORREO OUT STORES.EMAIL%TYPE,
    DIRECCION OUT STORES.STREET%TYPE
)
RETURN VARCHAR2
IS
    NOMBRE_TIENDA STORES.STORE_NAME%TYPE;
BEGIN
    SELECT STORE_NAME, PHONE, EMAIL, STREET 
    INTO NOMBRE_TIENDA, TELEFONO, CORREO, DIRECCION
    FROM STORES 
    WHERE STORE_ID=ID_TIENDA;

    RETURN NOMBRE_TIENDA;
END;

--EJECUCION
DECLARE
    NOMBRE_TIENDA STORES.STORE_NAME%TYPE;
    TELEFONO STORES.PHONE%TYPE;
    CORREO STORES.EMAIL%TYPE;
    DIRECCION STORES.STREET%TYPE;
BEGIN
    NOMBRE_TIENDA:=FN_DATOS_TIENDA(2, TELEFONO, CORREO, DIRECCION);
    DBMS_OUTPUT.PUT_LINE('EL NOMBRE DE LA TIENDA ES: ' || NOMBRE_TIENDA);
    DBMS_OUTPUT.PUT_LINE('EL TELEFONO DE LA TIENDA ES: ' || TELEFONO);
    DBMS_OUTPUT.PUT_LINE('EL CORREO DE LA TIENDA ES: ' || CORREO);
    DBMS_OUTPUT.PUT_LINE('EL NOMBRE DIRRECION DE LA TIENDA ES: ' || DIRECCION);
END;


--- FUNCION V2 ---
CREATE OR REPLACE FUNCTION FN_DATOS_REG_TIENDA(
    ID_TIENDA STORES.STORE_ID%TYPE
)
RETURN STORES%ROWTYPE
IS
    REGISTRO STORES%ROWTYPE;
BEGIN
    SELECT * 
    INTO REGISTRO
    FROM STORES 
    WHERE STORE_ID=ID_TIENDA;

    RETURN REGISTRO;
END;

--EJECUCION
DECLARE
    REG STORES%ROWTYPE;
BEGIN
    REG := FN_DATOS_REG_TIENDA(2);
    DBMS_OUTPUT.PUT_LINE('EL NOMBRE DE LA TIENDA ES: ' || REG.STORE_NAME);
    DBMS_OUTPUT.PUT_LINE('EL TELEFONO DE LA TIENDA ES: ' || REG.PHONE);
    DBMS_OUTPUT.PUT_LINE('EL CORREO DE LA TIENDA ES: ' || REG.EMAIL);
    DBMS_OUTPUT.PUT_LINE('EL NOMBRE DIRRECION DE LA TIENDA ES: ' || REG.STREET);
END;

