--CONSULTA TBL_GAME--
SELECT GM_ID, GM_NAME, ESTM_DURATION, TYPE_DESC, PRICE 
FROM TBL_GAME 
INNER JOIN TBL_CATEGORY 
ON TBL_CATEGORY.CAT_CODE = TBL_GAME.CAT_CODE;

--CONSULTA TBL_SALE--
SELECT SALE_ID, DISCOUNT, IS_GIFT 
FROM TBL_SALE 
INNER JOIN TBL_CATALOGUE 
ON TBL_SALE.CATLG_ID = TBL_CATALOGUE.CATLG_ID;

--CONSULTA TBL_USER
SELECT USER_ID, USERNAME, GENDER 
FROM TBL_USER;

--CONSULTA FECHA
SELECT CONVERT(DATE, SALE_DATE) DATE_ID, 
DATEPART(YEAR, SALE_DATE) YEAR,
DATEPART(MONTH, SALE_DATE) MONTH, 
DATEPART(DAY, SALE_DATE) DAY, 
DATEPART(WEEK, SALE_DATE) WEEK, 
DATEPART(QUARTER, SALE_DATE) TRIMESTER, 
((DATEPART(QUARTER,SALE_DATE)-1)/2)+1 SEMESTER,
DATENAME(WEEKDAY, SALE_DATE) WEEK_DAY 
From TBL_SALE
GROUP BY  TBL_SALE.SALE_DATE

--CONSULTA TABLA DE HECHOS
SELECT TBL_GAME.GM_ID, TBL_SALE.SALE_ID, TBL_USER.USER_ID,  
CONVERT(DATE, TBL_SALE.SALE_DATE) DATE_ID,
SUM(TBL_GAME_SESSION.TIME_PLAYED) TIME_PLAYED,
SUM(CAST((TBL_GAME.PRICE * (1 - TBL_CATALOGUE.DISCOUNT)) AS DECIMAL(10,2))) MOUNT
FROM TBL_SALE
INNER JOIN TBL_CATALOGUE ON TBL_SALE.CATLG_ID = TBL_CATALOGUE.CATLG_ID
INNER JOIN TBL_GAME ON TBL_CATALOGUE.GM_ID = TBL_GAME.GM_ID
INNER JOIN TBL_USER ON TBL_SALE.USER_ID = TBL_USER.USER_ID
INNER JOIN TBL_GAME_SESSION ON TBL_GAME_SESSION.USER_ID = TBL_USER.USER_ID
GROUP BY  TBL_GAME.GM_ID, TBL_SALE.SALE_ID, TBL_USER.USER_ID, TBL_SALE.SALE_DATE;

