CREATE TABLE TBL_GAME (
    GM_ID INT PRIMARY KEY,
    GM_NAME NVARCHAR(150),
    ESTM_DURATION INT,
    TYPE_DESC NVARCHAR(10),
    PRICE DECIMAL(8,2)
);

CREATE TABLE TBL_SALE(
    SALE_ID INT PRIMARY KEY,
    DISCOUNT DECIMAL(3,2),
    IS_GIFT BIT
);

CREATE TABLE TBL_USER(
    USER_ID INT PRIMARY KEY,
    USERNAME NVARCHAR(50),
    GENDER NVARCHAR(3)  
);

CREATE TABLE TBL_DATE(
    DATE_ID DATE PRIMARY KEY,
	YEAR INT NULL,
	MONTH INT NULL,
    DAY INT NULL,
	WEEK INT NULL,
	TRIMESTER INT NULL,
    SEMESTER INT NULL,
	WEEK_DAY NVARCHAR(20) NULL,
);

CREATE TABLE TBL_SALE_INFO(
    INFO_ID  INT IDENTITY PRIMARY KEY,
    GM_ID INT FOREIGN KEY REFERENCES TBL_GAME(GM_ID),
    SALE_ID INT FOREIGN KEY REFERENCES TBL_SALE(SALE_ID),
    USER_ID INT FOREIGN KEY REFERENCES TBL_USER(USER_ID),
    DATE_ID DATE FOREIGN KEY REFERENCES TBL_DATE(DATE_ID),
    TIME_PLAYED DECIMAL(10,2),
    MOUNT DECIMAL(10,2)
);

