CREATE TABLE  TBL_DEVELOPER (
    DEV_ID INT IDENTITY PRIMARY KEY,
    DEV_NAME NVARCHAR(50)
);

CREATE TABLE  TBL_CATEGORY (
    CAT_CODE NVARCHAR(10) PRIMARY KEY,
    TYPE_DESC NVARCHAR(10)
);

CREATE TABLE  TBL_GENRE (
    GNR_ID INT IDENTITY PRIMARY KEY,
    GNR_NAME NVARCHAR(50)
);

CREATE TABLE TBL_GAME (
    GM_ID INT IDENTITY PRIMARY KEY,
    GM_NAME NVARCHAR(150),
    RELEASE_DATE DATETIME,
    ESTM_DURATION INT,
    DEV_ID INT FOREIGN KEY REFERENCES TBL_DEVELOPER(DEV_ID),
    CAT_ID INT FOREIGN KEY REFERENCES TBL_CATEGORY(CAT_ID)
);

CREATE TABLE TBL_GAME_GENRE (
	GM_GNR_ID INT IDENTITY PRIMARY KEY,
    GM_ID INT FOREIGN KEY REFERENCES TBL_GAME(GM_ID),
    GNR_ID INT FOREIGN KEY REFERENCES TBL_GENRE(GNR_ID),
);

CREATE TABLE TBL_CATALOGUE (
	CATLG_ID INT IDENTITY PRIMARY KEY,
    DISCOUNT NUMBER(2,2),
    GM_ID INT FOREIGN KEY REFERENCES TBL_GAME(GM_ID),
);

CREATE TABLE TBL_USER(
    USER_ID INT IDENTITY PRIMARY KEY,
    USERNAME NVARCHAR(50),
    EMAIL NVARCHAR(50) UNIQUE, 
    PASSWORD NVARCHAR(50),
    IS_PLAYING BIT
);

CREATE TABLE TBL_GAME_OWNER(
    GM_OWNER_ID INT IDENTITY PRIMARY KEY,
    USER_ID INT FOREIGN KEY REFERENCES TBL_USER(USER_ID),
    GM_ID INT FOREIGN KEY REFERENCES TBL_GAME(GM_ID),
);

CREATE TABLE TBL_REVIEW(
    REV_ID INT IDENTITY PRIMARY KEY,
    GM_ID INT FOREIGN KEY REFERENCES TBL_GAME(GM_ID),
    REV_CONTENT NVARCHAR(500),
    RATE SMALLINT,
    DATE_CREATED DATETIME
);

CREATE TABLE TBL_GAME_SESSION(
    SESSION_ID INT IDENTITY PRIMARY KEY,
    USER_ID INT FOREIGN KEY REFERENCES TBL_USER(USER_ID),
    GM_ID INT FOREIGN KEY REFERENCES TBL_GAME(GM_ID),
    TIME_PLAYED DECIMAL(8,2),
    START_DATE DATETIME,
    END_DATE DATETIME 
);

CREATE TABLE TBL_SALE(
    SALE_ID INT IDENTITY PRIMARY KEY,
    CATLG_ID INT FOREIGN KEY REFERENCES TBL_CATALOGUE(CATLG_ID),
    USER_ID INT FOREIGN KEY REFERENCES TBL_USER(USER_ID),
    SALE_DATE DATETIME,
    IS_GIFT BIT
);

CREATE TABLE GAME_GIFT(
    GIFT_ID INT IDENTITY PRIMARY KEY,
    SALE_ID INT FOREIGN KEY REFERENCES TBL_SALE(SALE_ID),
    GIFT_OWNER INT FOREIGN KEY REFERENCES TBL_USER(USER_ID)
);


 


