--- CREAR PERMISOS PARA CREAR SECUENCIAS ---

--CONECTARSE CON EL USUARIO SYSTEM
GRANT CREATE ANY SEQUENCE, DROP ANY SEQUENCE TO ADMINISTRADORES;



------------------- BD_BICICLETAS -------------------------
SET SERVEROUTPUT ON;

--- CREACION DE SECUENCIAS
CREATE SEQUENCE SQ_TABLA_CATEGORIAS
START WITH 5
INCREMENT BY 1;


----- USANDO UNA SECUENCIA -----
-- USANDO UNA TABLA CON 7 VALORES CON SUS RESPECTIVOS ID ENTONCES =>

-- NEXTVAL: OBTENDRA EL VALOR ACTUAL DE LA SECUENCIA Y LO ALTERARA AL SIGUIENTE 

-- PRIMERA EJECUCION: ERROR VALOR DUPLICADO (VALOR ID 5)
-- SEGUNDA EJECUCION: ERROR VALOR DUPLICADO (VALOR ID 6)
-- TERCERA EJECUCION: ERROR VALOR DUPLICADO (VALOR ID 7)
-- CUARTA EJECUCION: VALOR INSERTADO EXITOSAMENTE (VALOR ID 8)
INSERT INTO CATEGORIES VALUES (SQ_TABLA_CATEGORIAS.NEXTVAL, 'BICICLETAS PROFESIONALES');


----- USANDOLO EN BLOQUE ANONIMO -----

DECLARE 
    VALOR_ACTUAL_SQ NUMBER;
BEGIN
    -- CURRVAL: OBTENDRA EL VALOR DE LA SECUENCIA SIN ALTERAR SU VALOR
    -- PARA HACER USO DE CURVAL PRIMERO HABRA QUE USAR ANTES ALMENOS UNA VEZ NEXTVAL
    
    VALOR_ACTUAL_SQ := SQ_TABLA_CATEGORIAS.CURRVAL;
    DBMS_OUTPUT.PUT_LINE('EL VALOR ACTUAL DE LA SECUENCIA ES: ' || VALOR_ACTUAL_SQ);
END;



