SET SERVEROUTPUT ON;

--- RECORD BASADO EN UNA TABLA
DECLARE
    FECHA DATE;
    FECHA_HORA TIMESTAMP;
BEGIN 
    FECHA:=SYSDATE;
    DBMS_OUTPUT.PUT_LINE('LA FECHA OBTENIDA CON SYSDATE ES: ' || FECHA);

    FECHA_HORA:=SYSTIMESTAMP;
    DBMS_OUTPUT.PUT_LINE('LA FECHA OBTENIDA CON SYSTIMESTAMP ES: ' || FECHA_HORA);


    ----- FUNCIONES PARA TIPOS DE DATOS DE TIEMPO -----

    -- ASIGNAR FECHAS
    FECHA := TO_DATE('2018-05-28', 'YYYY-MM-DD');
    DBMS_OUTPUT.PUT_LINE('LA FECHA ASIGNADA CON TO_DATE ES: ' || FECHA);

    FECHA_HORA := TO_TIMESTAMP('25-02-2020 11:30:16', 'DD-MM-YYYY HH:MI:SS');
    DBMS_OUTPUT.PUT_LINE('LA FECHA ASIGNADA CON TO_TIMESTAMP ES: ' || FECHA_HORA);

    -- CAMBIAR FORMATO DE LAS FECHAS
    DBMS_OUTPUT.PUT_LINE('USO DE TO_CHAR PARA CAMBIAR EL FORMATO DE IMPRESION DE FECHA: ' || 
    TO_CHAR(FECHA, 'YYYY-MM-DD'));
    
    DBMS_OUTPUT.PUT_LINE('USO DE TO_CHAR PARA CAMBIAR EL FORMATO DE IMPRESION DE FECHA Y HORA: ' ||
    TO_CHAR(FECHA_HORA, 'DD-MM-YYYY HH-MI-SS'));

    -- CAMBIAR FORMARO DE HORA
    DBMS_OUTPUT.PUT_LINE('USO DE TO_CHAR PARA CAMBIAR EL FORMATO DE IMPRESION DE HORA(24H): ' ||
    TO_CHAR(FECHA_HORA, 'DD-MM-YYYY HH24:MI:SS'));
     
    DBMS_OUTPUT.PUT_LINE('USO DE TO_CHAR PARA CAMBIAR EL FORMATO DE IMPRESION DE HORA(AM/PM): ' ||
    TO_CHAR(FECHA_HORA, 'DD-MM-YYYY HH:MI:SS AM'));

    -- FUNCION USUARIOS
    DBMS_OUTPUT.PUT_LINE('USARIO CONECTADO: ' || USER);
END;


---CONSULTAS

SELECT ORDER_DATE, TO_CHAR(TO_DATE(ORDER_DATE, 'YYYYMMDD'), 'YYYY-MM-DD'),
TO_TIMESTAMP(ORDER_DATE, 'YYYYMMDD HH:MI:SS') FROM ORDERS;

---SUBSTR(COLUMNA, DONDE INICIA, CUANTAS CARACTERES OBTIENE)
SELECT CATEGORY_NAME, SUBSTR(CATEGORY_NAME,1,5) FROM CATEGORIES;
