SET SERVEROUTPUT ON;


--- RECORD BASADO EN UNA TABLA
DECLARE
  TYPE ARREGLO IS TABLE OF VARCHAR(100) INDEX BY PLS_INTEGER;
  DATOS ARREGLO;
BEGIN
  DATOS(1):= 'ELEMENTO 1';
  DATOS(2):= 'ELEMENTO 2';
  DATOS(3):= 'ELEMENTO 3';
  DATOS(4):= 'ELEMENTO 4';
  DATOS(5):= 'ELEMENTO 5';
  DATOS(6):= 'ELEMENTO 5';

  FOR ITERACION IN 1..DATOS.COUNT LOOP
    DBMS_OUTPUT.PUT_LINE(DATOS(ITERACION));
  END LOOP;

  --------- MAS FUNCIONES ---------

  -- VALOR ANTERIOR AL INDICE DEL PARAMETRO
  DBMS_OUTPUT.PUT_LINE('PRIOR: ' || DATOS.PRIOR(3));

  -- VALOR SIGUIENTE AL INDICE DEL PARAMETRO 
  DBMS_OUTPUT.PUT_LINE('NEXT: ' || DATOS.NEXT(3)); 

  -- BORRAR ELEMENTO EN EL INDICE DEL PARAMETRO
  DATOS.DELETE(1);
  DBMS_OUTPUT.PUT_LINE('ELIMINADO VALOR DEL INDICE 1'); 
  DBMS_OUTPUT.PUT_LINE('LA CANTIDAD DE VALORES ES: ' || DATOS.COUNT); 
  DBMS_OUTPUT.PUT_LINE('DATO EN EL INDICE 2: ' || DATOS(2)); 
  -- DBMS_OUTPUT.PUT_LINE('DATO EN EL INDICE 1: ' || DATOS(1)); -- TIRA ERROR 

  DATOS.DELETE(2,4);
  DBMS_OUTPUT.PUT_LINE('ELIMINADO VALOR DEL INDICE 2 AL 4'); 
  DBMS_OUTPUT.PUT_LINE('LA CANTIDAD DE VALORES ES: ' || DATOS.COUNT); 

END;