SET SERVEROUTPUT ON;

------ BITACORA --------

-- El ejercicio consiste en construir una tabla de bitacora el cual almacene todos 
-- los cambios que ocurren en la base de datos.

-- CREACION DE LA TABLA PARA GUARDAR LOS REGISTROS
CREATE TABLE BITACORAS(
    PK_CODE_BITACORA NUMBER PRIMARY KEY,
    DESCRIPCION VARCHAR2(2000),
    FECHA_HORA TIMESTAMP,
    USUARIO VARCHAR(100),
    OPERACION VARCHAR(50)
);

-- CREAR SECUENCIA PARA LA LLAVE PRIMARIA DE LA TABLA DEW BITACORAS
CREATE SEQUENCE SQ_BITACORAS
START WITH 1
INCREMENT BY 1;


-- TRIGGER QUE CREA UN REGISTRO POR CADA INSERT A LA TABLA CATEGORIAS
CREATE OR REPLACE TRIGGER TG_CATEGORIAS
AFTER INSERT ON CATEGORIES
FOR EACH ROW
DECLARE
    -- TRANSACCION AUTONOMA
    -- SEPARA LAS DISTINTAS TRANSACCIONES QUE PUEDAN OCURRIR EN UNA OPERACION
    PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN
    INSERT INTO BITACORAS VALUES (SQ_BITACORAS.NEXTVAL, 'SE REALIZO UN INSERT EN LA TABLA CATEGORIAS Y EL DATO NUEVO EN EL ID ES: ' ||
    :NEW.CATEGORY_ID || 'Y EL NOMBRE DE LA CATEGORIA ES: ' || :NEW.CATEGORY_NAME, 
    SYSTIMESTAMP, USER, 'OPERACION INSERT');
    COMMIT;

    EXCEPTION 
        WHEN OTHERS THEN
            ROLLBACK;

END;


BEGIN
    INSERT INTO CATEGORIES (CATEGORY_NAME) VALUES ('BICICLETAS PLAYERAS');
    COMMIT;
END;




