SET SERVEROUTPUT ON;
---- GESTION DE TRANSACCIONES (COMMIT/ROLLBACK) ----

DECLARE

BEGIN 
    INSERT INTO BRANDS VALUES (13, 'MOUNTAIN BCI');
    COMMIT; 

    INSERT INTO BRANDS VALUES (14, 'BICI SHOP');
    COMMIT;

    INSERT INTO BRANDS VALUES (12, 'ELECTRO');
    COMMIT;

    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            DBMS_OUTPUT.PUT_LINE('ERROR DE LLAVE PRIMARIA');
            ROLLBACK;
END;

---- SAVEPOINTS ----

DECLARE

BEGIN 

    -- SE CREA UN PUNTO DE GUARDADO 
    UPDATE BRANDS SET BRAND_NAME = BRAND_NAME || ' 2019' WHERE BRAND_ID=1;
    UPDATE BRANDS SET BRAND_NAME = BRAND_NAME || ' 2019' WHERE BRAND_ID=2;
    
    COMMIT;
    SAVEPOINT DATOS_MODIFICADOS;
    
    -- GENERA UN ERROR Y NO SE GUARDA EL PUNTO DE GUARDADO
    UPDATE BRANDS SET BRAND_ID = 1, BRAND_NAME = BRAND_NAME || ' 2021' 
    WHERE BRAND_ID=14;

    COMMIT;
    SAVEPOINT DATOS_MODIFICADOS;


    -- EL PUNTO DE GUARDADO JAMAS LLEGA AQUI
    UPDATE BRANDS SET BRAND_NAME = BRAND_NAME || ' 2020' 
    WHERE BRAND_ID=12 OR BRAND_ID=13;

    COMMIT;
    SAVEPOINT DATOS_MODIFICADOS;
    
    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            DBMS_OUTPUT.PUT_LINE('ERROR DE LLAVE PRIMARIA');

            --REGRESA EL ESTADO DE LA TABLA AL ULTIMO PUNTO DE GUARDADO EXITOSO
            ROLLBACK TO SAVEPOINT DATOS_MODIFICADOS; 
END;