SET SERVEROUTPUT ON;

CREATE OR REPLACE FUNCTION FN_INF_CLIENTE_20181005735( TOTAL_CLIENTE OUT NUMBER  )
RETURN SYS_REFCURSOR
IS
    CDATOS SYS_REFCURSOR;
BEGIN

    SELECT COUNT(*) INTO TOTAL_CLIENTE FROM CLIENTES WHERE DIRECCIONCLI = 'AV.AMAZONAS';

    OPEN CDATOS FOR 
    SELECT * FROM CLIENTES WHERE DIRECCIONCLI = 'AV.AMAZONAS';

    RETURN CDATOS;
END;
/

---EJECUCION 
DECLARE
    DATOS_CAT SYS_REFCURSOR;

    CLIENTEID CLIENTES.CLIENTEID%TYPE;
    CEDULA_RUC CLIENTES.CEDULA_RUC%TYPE;
    NOMBRECIA CLIENTES.NOMBRECIA%TYPE;
    NOMBRECONTACTO CLIENTES.NOMBRECONTACTO%TYPE;
    DIRECCIONCLI CLIENTES.DIRECCIONCLI%TYPE;
    FAX CLIENTES.FAX%TYPE;
    EMAIL CLIENTES.EMAIL%TYPE;
    CELULAR CLIENTES.CELULAR%TYPE;
    FIJO CLIENTES.FIJO%TYPE;

    TOTAL_CLIENTE NUMBER;
BEGIN
    DATOS_CAT := FN_INF_CLIENTE_20181005735(TOTAL_CLIENTE);
    
    DBMS_OUTPUT.PUT_LINE(' ');
    DBMS_OUTPUT.PUT_LINE('-------------------------------------------------------------------------- ');
    DBMS_OUTPUT.PUT_LINE('INFORMACION CLIENTE DEL CURSOR ');
    DBMS_OUTPUT.PUT_LINE('-------------------------------------------------------------------------- ');

    LOOP
        FETCH DATOS_CAT 
        INTO 
            CLIENTEID,
            CEDULA_RUC,
            NOMBRECIA,
            NOMBRECONTACTO,
            DIRECCIONCLI,
            FAX,
            EMAIL,
            CELULAR,
            FIJO
        ;

        EXIT WHEN DATOS_CAT%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE(' ');
        DBMS_OUTPUT.PUT_LINE('EL ID DEL CLIENTE ES: ' || CLIENTEID);
        DBMS_OUTPUT.PUT_LINE('LA CEDULA ES: ' || CEDULA_RUC);
        DBMS_OUTPUT.PUT_LINE('LA NOMBRECIA: ' || NOMBRECIA);
        DBMS_OUTPUT.PUT_LINE('EL NOMBRE DEL CONTACTO ES: ' || NOMBRECONTACTO);
        DBMS_OUTPUT.PUT_LINE('LA DIRRECION ES: ' || DIRECCIONCLI);
        --DBMS_OUTPUT.PUT_LINE('EL FAX ES: ' || FAX);
        --DBMS_OUTPUT.PUT_LINE('EL EMAIL ES: ' || EMAIL);
        --DBMS_OUTPUT.PUT_LINE('EL CELULAR ES: ' || CELULAR);
        --DBMS_OUTPUT.PUT_LINE('EL FIJO ES: ' || FIJO);
      
       
        

    END LOOP;
    DBMS_OUTPUT.PUT_LINE(' ');
    DBMS_OUTPUT.PUT_LINE('-------------------------------------------------------------------------- ');
    DBMS_OUTPUT.PUT_LINE('EL TOTAL DE CLIENTES QUE VIVEN EN EL AV. AMAZONAS ES : ' || TOTAL_CLIENTE);
    DBMS_OUTPUT.PUT_LINE('-------------------------------------------------------------------------- ');
END;
/


