SET SERVEROUTPUT ON;

-----ENCABEZADO------
CREATE OR REPLACE PACKAGE PK_INF_PEDIDOS_20181005735 
IS
    PROCEDURE SP_INSERT_CATEGORY_20181005735 (
        CATEGORIAID CATEGORIAS.CATEGORIAID%TYPE,
        NOMBRECAT CATEGORIAS.NOMBRECAT%TYPE,
        MSJ OUT NUMBER
    );
    
    FUNCTION FN_TOTAL_PRODUCTO_20181005725 ( TOTAL_EXISTENCIA NUMBER )
    RETURN NUMBER;
END;
/

-----CUERPO------
CREATE OR REPLACE PACKAGE BODY PK_INF_PEDIDOS_20181005735
IS
    PROCEDURE SP_INSERT_CATEGORY_20181005735 (
        CATEGORIAID CATEGORIAS.CATEGORIAID%TYPE,
        NOMBRECAT CATEGORIAS.NOMBRECAT%TYPE,
        MSJ OUT NUMBER
    )
    IS
    BEGIN
        INSERT INTO CATEGORIAS VALUES (
            CATEGORIAID,
            NOMBRECAT
        );

        COMMIT;       
        MSJ:=1;

        EXCEPTION
            WHEN OTHERS THEN
            ROLLBACK;
            MSJ:=2;
    END;


    FUNCTION FN_TOTAL_PRODUCTO_20181005725 ( TOTAL_EXISTENCIA NUMBER )
    RETURN NUMBER
    IS
        TOTAL_PRODUCTO NUMBER;
    BEGIN 
      
        SELECT COUNT(*) INTO TOTAL_PRODUCTO
        FROM PRODUCTOS
        WHERE EXISTENCIA = TOTAL_EXISTENCIA;

      
        RETURN TOTAL_PRODUCTO;
    END;
    
END;
/


--EJECUCCION
DECLARE 
    TOTAL_PRODUCTO NUMBER;
    MSJ NUMBER;
BEGIN
    DBMS_OUTPUT.PUT_LINE(' ');
    DBMS_OUTPUT.PUT_LINE('PRUEBA FUNCION');
    TOTAL_PRODUCTO := PK_INF_PEDIDOS_20181005735.FN_TOTAL_PRODUCTO_20181005725(200);
    DBMS_OUTPUT.PUT_LINE('LA CANTIDAD DE PRODUCTOS CON 200 DE EXISTENCIA ES: ' || TOTAL_PRODUCTO);
    

    DBMS_OUTPUT.PUT_LINE(' ');
    DBMS_OUTPUT.PUT_LINE('PRUEBA PROCEDIMIENTO ALMACENADO');
    PK_INF_PEDIDOS_20181005735.SP_INSERT_CATEGORY_20181005735(
        '800', 
        'FRUTAS',
        MSJ
    );
    IF (MSJ = 1) THEN
        DBMS_OUTPUT.PUT_LINE('LA CATEGORIA FUE INSERTADA');
    ELSIF (MSJ = 2) THEN
        DBMS_OUTPUT.PUT_LINE('SURGIO UN ERROR CUANDO SE INTENTO INSERTAR LA CATEGORIA');
    END IF;

END;
/