--CREACION DE JOB
BEGIN
DBMS_SCHEDULER.CREATE_JOB(
    JOB_NAME => 'JOB_DIETAS_OBSOLETAS',
    JOB_TYPE => 'STORED_PROCEDURE',
    JOB_ACTION => 'SP_DIETAOBSOLETA',
    NUMBER_OF_ARGUMENTS => 0,
    START_DATE => TO_TIMESTAMP('2021-05-1 11:50:00', 'YYYY-MM-DD HH24:MI:SS' ),
    REPEAT_INTERVAL => 'FREQ=MONTHLY; BYMONTHDAY=1; BYHOUR=11; BYMINUTE=50; BYSECOND=0',
    ENABLED => TRUE
);
END;

--PRUEBA DE JOB
BEGIN
    DBMS_SCHEDULER.RUN_JOB(
        JOB_NAME => 'JOB_DIETAS_OBSOLETAS'
    );
END;