--TABLA BITACORAS
CREATE TABLE TBL_BITACORAS_20181005735(
    ID NUMBER PRIMARY KEY,
    DESCRIPCION VARCHAR2(2000),
    FECHA_HORA TIMESTAMP,
    USUARIO VARCHAR(100),
    OPERACION VARCHAR(50)
);

--TABLA SECUENCIAS
CREATE SEQUENCE SQ_BITACORAS_20181005735
START WITH 1
INCREMENT BY 1;



-- TRIGGER ID BITACORA
CREATE OR REPLACE TRIGGER TG_BITACORAS_20181005735
BEFORE INSERT ON TBL_BITACORAS_20181005735
FOR EACH ROW
BEGIN
    :NEW.ID := SQ_BITACORAS_20181005735.NEXTVAL;
END;
/

--TRIGGERS EMP 
CREATE OR REPLACE TRIGGER TG_EMP_INSERT_20181005735
AFTER INSERT ON EMP
FOR EACH ROW
BEGIN
    INSERT INTO TBL_BITACORAS_20181005735
    (
        FECHA_HORA,
        DESCRIPCION, 
        USUARIO, 
        OPERACION 
    ) 
    VALUES (
        SYSTIMESTAMP,
        'SE INSERTO UN VALOR EN LA TABLA EMPLEADO',
        USER, 
        'INSERT'
    );
END;
/

CREATE OR REPLACE TRIGGER TG_EMP_UPDATE_20181005735
AFTER UPDATE ON EMP
FOR EACH ROW
BEGIN
    INSERT INTO TBL_BITACORAS_20181005735
    (
        FECHA_HORA,
        DESCRIPCION, 
        USUARIO, 
        OPERACION 
    ) 
    VALUES (
        SYSTIMESTAMP,
        'SE ACTUALIZO UN VALOR EN LA TABLA EMPLEADO',
        USER, 
        'UPDATE'
    );
END;
/

CREATE OR REPLACE TRIGGER TG_EMP_DELETE_20181005735
AFTER DELETE ON EMP
FOR EACH ROW
BEGIN
    INSERT INTO TBL_BITACORAS_20181005735
    (
        FECHA_HORA,
        DESCRIPCION, 
        USUARIO, 
        OPERACION 
    ) 
    VALUES (
        SYSTIMESTAMP,
        'SE ELIMINO UN VALOR EN LA TABLA EMPLEADO',
        USER, 
        'DELETE'
    );
END;
/


DECLARE
BEGIN
  --PRUEBAS
  INSERT INTO EMP VALUES ('1', 'JOSUE', 'ENGINEER', 7839, SYSDATE, 1000, 0, 10);
  UPDATE EMP SET ENAME = 'GABRIEL' WHERE EMPNO=1;
  DELETE FROM EMP WHERE  EMPNO = 1;
END;