SET SERVEROUTPUT ON;

CREATE TABLE TBL_REG_CLI_20181005735(
    CUSTOMER_ID  NUMBER PRIMARY KEY,
    CUST_FIRST_NAME VARCHAR2(20),
    CUST_STREET_ADDRESS1 VARCHAR2(60),
    CUST_CITY VARCHAR2(30),
    UPDATE_DATE TIMESTAMP DEFAULT SYSTIMESTAMP
);

DECLARE
    TYPE FILA IS RECORD(
        CUSTOMER_ID  DEMO_CUSTOMERS.CUSTOMER_ID%TYPE,
        CUST_FIRST_NAME DEMO_CUSTOMERS.CUST_FIRST_NAME%TYPE,
        CUST_STREET_ADDRESS1 DEMO_CUSTOMERS.CUST_STREET_ADDRESS1%TYPE,
        CUST_CITY DEMO_CUSTOMERS.CUST_CITY%TYPE
    );

    TYPE TABLA_CUSTOMERS IS TABLE OF FILA INDEX BY PLS_INTEGER;
    DATOS_CUSTOMERS TABLA_CUSTOMERS;
    ITERACION NUMBER(10) := 0;
    MAX_ITERACION NUMBER;

BEGIN 
    SELECT 
    CUSTOMER_ID,
    CUST_FIRST_NAME,
    CUST_STREET_ADDRESS1,
    CUST_CITY
    BULK COLLECT INTO DATOS_CUSTOMERS
    FROM DEMO_CUSTOMERS;
    
  
    MAX_ITERACION := SQL%ROWCOUNT;
    WHILE  (ITERACION<MAX_ITERACION) LOOP

        INSERT INTO TBL_REG_CLI_20181005735 
        (
            CUSTOMER_ID,
            CUST_FIRST_NAME,
            CUST_STREET_ADDRESS1,
            CUST_CITY
        ) VALUES (
            DATOS_CUSTOMERS(ITERACION+1).CUSTOMER_ID,
            DATOS_CUSTOMERS(ITERACION+1).CUST_FIRST_NAME,
            DATOS_CUSTOMERS(ITERACION+1).CUST_STREET_ADDRESS1,
            DATOS_CUSTOMERS(ITERACION+1).CUST_CITY
        );
        
        DBMS_OUTPUT.PUT_LINE(' ');      
        DBMS_OUTPUT.PUT_LINE('SE AGREGO EL CLIENTE: ' || DATOS_CUSTOMERS(ITERACION+1).CUST_FIRST_NAME);
        ITERACION:=ITERACION+1;       
        
    END LOOP;
    
    EXCEPTION
      WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('SE ESTAN AGREGANDO VALORES DUPLICADOS');
          ROLLBACK;
          DBMS_OUTPUT.PUT_LINE('ERROR: ' || SQLERRM);
        
END;
/