
-- DROPS


--TRIGGER 1
CREATE OR REPLACE TRIGGER TG_EMP_INSERT --CAMBIAR NOMBRE (NO ES ERROR)
AFTER INSERT ON EMPLOYEES
FOR EACH ROW
DECLARE
    -- TRANSACCION AUTONOMA
    PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN

    -- DEFINIR LA ESTRUCTURA DE LOS DATOS DE ENTRADA 
    INSERT INTO REGISTRO_LOGS 
    (   
        FECHA_LOG,
        DESCRIPCION_LOG,
        USUARIO,
        TIPO_OPERACION,
        TABLA_AFECTADA
    ) 
    VALUES (
        SYSDATE, 
        'SE INSERTÓ UN NUEVO REGISTRO EN LA TABLA EMPLEADOS', 
        USER, 
        'INSERT', 
        'EMPLEADOS'
    );

    COMMIT;

    EXCEPTION 
        WHEN OTHERS THEN  -- AGREGAR CONDICION DE EXCEPCIONES
            ROLLBACK;
END;
/

-- TRIGGER 2
CREATE OR REPLACE TRIGGER TG_DEPTS_UPDATE  --CAMBIAR NOMBRE (NO ES ERROR)
BEFORE UPDATE ON DEPARTMENTS -- CAMBIAR TABLA
FOR EACH ROW
BEGIN

    INSERT INTO REGISTRO_LOGS
    (
        FECHA_LOG,
        DESCRIPCION_LOG,
        USUARIO,
        TIPO_OPERACION,
        TABLA_AFECTADA
    ) 
    VALUES (
        SYSDATE, 
        'SE ACTUALIZÓ UN REGISTRO EN LA TABLA DEPARTMENTS', 
        USER, -- CORECCION DE FUNCION
        'UPDATE', 
        'DEPARTMENTS'
    );
    -- SE AGREGO COMILLAS EN ALGUNOS VALORES
END;
/

-- TRIGGER 3
CREATE OR REPLACE TRIGGER TG_JOB_HISTORY_DELETE  --CAMBIAR NOMBRE (NO ES ERROR)
BEFORE DELETE ON JOB_HISTORY
FOR EACH ROW
BEGIN
    INSERT INTO REGISTRO_LOGS 
    (
        FECHA_LOG, 
        DESCRIPCION_LOG, 
        USUARIO, 
        TIPO_OPERACION, 
        TABLA_AFECTADA
    ) 
    VALUES (
        SYSDATE,
        'SE ELIMINÓ UN REGISTRO EN LA TABLA JOBS_HISTORY',
        USER, -- CORECCION DE FUNCION
        'DELETE', 
        'JOB_HISTORY'
    );
    -- SE AGREGO COMILLAS EN ALGUNOS VALORES
END;
/

-- INSERT INTO EMPLOYEES VALUES (SQ_EMPLOYEES.NEXTVAL, 'SUE', 'JINEZ', 'menez.josue@gmail.com', '88298881', SYSDATE , 'ST_CLERK', 13000, NULL, 100, 90); 
-- UPDATE DEPARTMENTS SET DEPARTMENT_NAME = 'TECH INFORMATION' WHERE DEPARTMENT_ID=60; 
-- DELETE FROM JOB_HISTORY WHERE EMPLOYEE_ID = 200;