SET SERVEROUTPUT ON;

DECLARE
    TYPE FILA IS RECORD(
        JOB_ID  JOBS.JOB_ID%TYPE,
        JOB_TITLE JOBS.JOB_TITLE%TYPE,
        MIN_SALARY JOBS.MIN_SALARY%TYPE,
        MAX_SALARY JOBS.MAX_SALARY%TYPE,
        DEPARTMENT_ID DEPARTMENTS.DEPARTMENT_ID%TYPE,
        DEPARTMENT_NAME DEPARTMENTS.DEPARTMENT_NAME%TYPE,
        START_DATE JOB_HISTORY.START_DATE%TYPE,
        END_DATE JOB_HISTORY.END_DATE%TYPE,
        FULL_NAME VARCHAR(45)
    );
    TYPE TABLA_EMPLEADO IS TABLE OF FILA INDEX BY PLS_INTEGER;
    DATOS_EMPLEADOS TABLA_EMPLEADO;
    ITERACION NUMBER(10) := 0;

BEGIN 
    SELECT 
    JOBS.JOB_ID, 
    JOBS.JOB_TITLE,
    JOBS.MIN_SALARY, 
    JOBS.MAX_SALARY, 
    DEPARTMENTS.DEPARTMENT_ID, 
    DEPARTMENTS.DEPARTMENT_NAME,
    JOB_HISTORY.START_DATE, 
    JOB_HISTORY.END_DATE,
    (EMPLOYEES.FIRST_NAME || ' ' || EMPLOYEES.LAST_NAME)
    BULK COLLECT INTO DATOS_EMPLEADOS
    FROM EMPLOYEES 
    INNER JOIN JOBS ON EMPLOYEES.JOB_ID = JOBS.JOB_ID 
    INNER JOIN DEPARTMENTS ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID
    INNER JOIN JOB_HISTORY ON EMPLOYEES.EMPLOYEE_ID = JOB_HISTORY.EMPLOYEE_ID  ;
  
  
    WHILE  (ITERACION<SQL%ROWCOUNT) LOOP
        DBMS_OUTPUT.PUT_LINE(' ');
        DBMS_OUTPUT.PUT_LINE('--------------------------- ELEMENTO ' || (ITERACION+1) || ' ---------------------------------');
        DBMS_OUTPUT.PUT_LINE('EL CODIGO DEL TRABAJO ES: ' || DATOS_EMPLEADOS(ITERACION+1).JOB_ID);
        DBMS_OUTPUT.PUT_LINE('EL TITULO DEL TRABAJO ES: ' || DATOS_EMPLEADOS(ITERACION+1).JOB_TITLE);
        DBMS_OUTPUT.PUT_LINE('EL SALARIO MINIMO DEL TRABAJO ES: ' || DATOS_EMPLEADOS(ITERACION+1).MIN_SALARY);
        DBMS_OUTPUT.PUT_LINE('EL SALARIO MAXIMO DEL TRABAJO ES: ' || DATOS_EMPLEADOS(ITERACION+1).MAX_SALARY);
        DBMS_OUTPUT.PUT_LINE('EL CODIGO DEL DEPARTAMENTO: ' || DATOS_EMPLEADOS(ITERACION+1).DEPARTMENT_ID);
        DBMS_OUTPUT.PUT_LINE('EL NOMBRE DEL DEPARTAMENTO ES: ' || DATOS_EMPLEADOS(ITERACION+1).DEPARTMENT_NAME);
        DBMS_OUTPUT.PUT_LINE('LA FECHA DE INICIO DEL EMPLEADO ES: ' || DATOS_EMPLEADOS(ITERACION+1).START_DATE);
        DBMS_OUTPUT.PUT_LINE('LA FECHA DE FINALIZACION DEL EMPLEADO ES: ' || DATOS_EMPLEADOS(ITERACION+1).END_DATE);
        DBMS_OUTPUT.PUT_LINE('EL NOMBRE COMPLETO DEL EMPLEADO ES: ' || DATOS_EMPLEADOS(ITERACION+1).FULL_NAME);
        DBMS_OUTPUT.PUT_LINE('-------------------------------------------------------------------------');
        ITERACION:=ITERACION+1;
        
    END LOOP;

END;
