SET SERVEROUTPUT ON;

DECLARE 
  NOMBRE PRODUCTS.PRODUCT_NAME%TYPE;
  MODELO PRODUCTS.MODEL_YEAR%TYPE;
  PRECIO PRODUCTS.LIST_PRICE%TYPE;
BEGIN
  SELECT PRODUCT_NAME, MODEL_YEAR, LIST_PRICE INTO NOMBRE, MODELO, PRECIO FROM PRODUCTS WHERE PRODUCT_ID=1;
  
  DBMS_OUTPUT.PUT_LINE('El nombre del producto con ID 1 es: ' || NOMBRE);
  DBMS_OUTPUT.PUT_LINE('El nombre del producto con ID 1 es: ' || MODELO);
  DBMS_OUTPUT.PUT_LINE('El nombre del producto con ID 1 es: ' || PRECIO);
END;