SET SERVEROUTPUT ON;

DECLARE 
  NOMBRE_PRODUCTO PRODUCTS.PRODUCT_NAME%TYPE;
  CURSOR CNOMBRE_PRODUCTO IS SELECT PRODUCT_NAME FROM PRODUCTS;
    
BEGIN
  OPEN CNOMBRE_PRODUCTO;
  
  LOOP
    FETCH CNOMBRE_PRODUCTO INTO NOMBRE_PRODUCTO;
    
    EXIT WHEN CNOMBRE_PRODUCTO%NOTFOUND;
    DBMS_OUTPUT.PUT_LINE('El nombre del producto es: ' || NOMBRE_PRODUCTO);  
    DBMS_OUTPUT.PUT_LINE('La cantidad de registors es: ' || CNOMBRE_PRODUCTO%ROWCOUNT);  
  END LOOP;
  
  
  CLOSE CNOMBRE_PRODUCTO;

END;