
-------------RECORDS----------------------

SET SERVEROUTPUT ON;

DECLARE 
  TYPE FILA IS RECORD(
    NOMBRE_PRODUCTO PRODUCTS.PRODUCT_NAME%TYPE,
    NOMBRE_CATEGORIA CATEGORIES.CATEGORY_NAME%TYPE,
    ANIO_MODELO NUMBER,
    COD_CATEGORIA NUMBER
  );
  
  CURSOR CDATOS_PRODUCTO IS SELECT PRODUCT_NAME, CATEGORIES.CATEGORY_NAME, 
  PRODUCTS.MODEL_YEAR, CATEGORIES.CATEGORY_ID FROM PRODUCTS 
  INNER JOIN CATEGORIES ON PRODUCTS.CATEGORY_ID=CATEGORIES.CATEGORY_ID;
  
  DATOS_CURSOR FILA;
BEGIN
  OPEN CDATOS_PRODUCTO;
 
   
  LOOP
    FETCH CDATOS_PRODUCTO INTO DATOS_CURSOR;
    
    EXIT WHEN CDATOS_PRODUCTO%NOTFOUND;
    DBMS_OUTPUT.PUT_LINE('El nombre del producto es: ' || DATOS_CURSOR.NOMBRE_PRODUCTO);  
    DBMS_OUTPUT.PUT_LINE('El modelo del producto es: ' || DATOS_CURSOR.ANIO_MODELO);  
    DBMS_OUTPUT.PUT_LINE('La categoria del producto es: ' ||  DATOS_CURSOR.NOMBRE_CATEGORIA);  
    DBMS_OUTPUT.PUT_LINE('El ID de la categoria del producto es: ' ||  DATOS_CURSOR.COD_CATEGORIA);  
    
    DBMS_OUTPUT.PUT_LINE(CHR(13));  
     
  END LOOP;
  
  CLOSE CDATOS_PRODUCTO;

END;


---------------BULK COLLECT-------------
SET SERVEROUTPUT ON;

DECLARE 
  TYPE FILA IS RECORD(
    CODIGO_CATEGORIA CATEGORIES.CATEGORY_NAME%TYPE,
    NOMBRE_CATEGORIA CATEGORIES.CATEGORY_NAME%TYPE
  );
  TYPE TABLA_CATEGORIAS IS TABLE OF FILA INDEX BY PLS_INTEGER;
  DATOS_CATEGORIA TABLA_CATEGORIAS;
  ITERACION NUMBER(10) := 0;
BEGIN
  SELECT CATEGORIES.CATEGORY_ID, CATEGORIES.CATEGORY_NAME 
  BULK COLLECT INTO DATOS_CATEGORIA FROM CATEGORIES;
  
  DBMS_OUTPUT.PUT_LINE('LA CANTIDAD DE REGISTROS ES: ' || SQL%ROWCOUNT);
  
  WHILE  (ITERACION<SQL%ROWCOUNT) LOOP
    DBMS_OUTPUT.PUT_LINE('EL CODIGO DE LA CATEGORIA ES: ' || DATOS_CATEGORIA(ITERACION+1).CODIGO_CATEGORIA);
    DBMS_OUTPUT.PUT_LINE('EL NOMBRE DE LA CATEGORIA ES: ' || DATOS_CATEGORIA(ITERACION+1).NOMBRE_CATEGORIA);
    ITERACION:=ITERACION+1;
  END LOOP;
 

END;