SET SERVEROUTPUT ON;


--- CURSOR CON MULTIPLE VARIABLES ---

DECLARE 
  NOMBRE_PRODUCTO PRODUCTS.PRODUCT_NAME%TYPE;
  MODELO_PRODUCTO PRODUCTS.MODEL_YEAR%TYPE;
  NOMBRE_CATEGORIA CATEGORIES.CATEGORY_NAME%TYPE;
  CURSOR CDATOS_PRODUCTO IS SELECT PRODUCT_NAME, CATEGORIES.CATEGORY_NAME, PRODUCTS.MODEL_YEAR 
  FROM PRODUCTS INNER JOIN CATEGORIES ON PRODUCTS.CATEGORY_ID=CATEGORIES.CATEGORY_ID;
    
BEGIN
  OPEN CDATOS_PRODUCTO;
  
  LOOP
    FETCH CDATOS_PRODUCTO INTO NOMBRE_PRODUCTO, NOMBRE_CATEGORIA, MODELO_PRODUCTO;
    
    EXIT WHEN CDATOS_PRODUCTO%NOTFOUND;
    DBMS_OUTPUT.PUT_LINE('El nombre del producto es: ' || NOMBRE_PRODUCTO);  
    DBMS_OUTPUT.PUT_LINE('El modelo del producto es: ' || MODELO_PRODUCTO);  
    DBMS_OUTPUT.PUT_LINE('La categoria del producto es: ' ||  NOMBRE_CATEGORIA);  
    DBMS_OUTPUT.PUT_LINE(CHR(13));  
  END LOOP;
  
  
  CLOSE CDATOS_PRODUCTO;

END;


---- CURSOR CON MULTIPLE VARIABLES USANDO ROWTYPE ----

SET SERVEROUTPUT ON;

DECLARE 
  
  CURSOR CDATOS_PRODUCTO IS SELECT PRODUCT_NAME, CATEGORIES.CATEGORY_NAME, PRODUCTS.MODEL_YEAR 
  FROM PRODUCTS INNER JOIN CATEGORIES ON PRODUCTS.CATEGORY_ID=CATEGORIES.CATEGORY_ID;
  
  REGISTRO CDATOS_PRODUCTO%ROWTYPE;

BEGIN
  OPEN CDATOS_PRODUCTO;
  
  LOOP
    FETCH CDATOS_PRODUCTO INTO REGISTRO;
    
    EXIT WHEN CDATOS_PRODUCTO%NOTFOUND;
    DBMS_OUTPUT.PUT_LINE('El nombre del producto es: ' || REGISTRO.PRODUCT_NAME);  
    DBMS_OUTPUT.PUT_LINE('El modelo del producto es: ' || REGISTRO.MODEL_YEAR);  
    DBMS_OUTPUT.PUT_LINE('La categoria del producto es: ' ||  REGISTRO.CATEGORY_NAME);  
    DBMS_OUTPUT.PUT_LINE(CHR(13));  
     
  END LOOP;
  
  
  CLOSE CDATOS_PRODUCTO;

END;

---- AMBIGUEDADES ---

SET SERVEROUTPUT ON;

DECLARE 
  
  CURSOR CDATOS_PRODUCTO IS SELECT PRODUCT_NAME, CATEGORIES.CATEGORY_NAME, 
  PRODUCTS.MODEL_YEAR, CATEGORIES.CATEGORY_ID CAT_ID, PRODUCTS.CATEGORY_ID PROD_CAT_ID
  FROM PRODUCTS INNER JOIN CATEGORIES ON PRODUCTS.CATEGORY_ID=CATEGORIES.CATEGORY_ID;
  
  REGISTRO CDATOS_PRODUCTO%ROWTYPE;
BEGIN
  OPEN CDATOS_PRODUCTO;
  
  LOOP
    FETCH CDATOS_PRODUCTO INTO REGISTRO;
    
    EXIT WHEN CDATOS_PRODUCTO%NOTFOUND;
    DBMS_OUTPUT.PUT_LINE('El nombre del producto es: ' || REGISTRO.PRODUCT_NAME);  
    DBMS_OUTPUT.PUT_LINE('El modelo del producto es: ' || REGISTRO.MODEL_YEAR);  
    DBMS_OUTPUT.PUT_LINE('La categoria del producto es: ' ||  REGISTRO.CATEGORY_NAME);  
    DBMS_OUTPUT.PUT_LINE('El ID de la categoria del producto es: ' ||  REGISTRO.CAT_ID);  
    DBMS_OUTPUT.PUT_LINE('El ID de la categoria del producto es: ' ||  REGISTRO.PROD_CAT_ID);
    DBMS_OUTPUT.PUT_LINE(CHR(13));  
     
  END LOOP;
  
  
  CLOSE CDATOS_PRODUCTO;

END;