SET SERVEROUTPUT ON;

CREATE OR REPLACE PROCEDURE SP_VALORES_REG_STAFF (
    ID_STAFF NUMBER,
    PRIM_NOMBRE VARCHAR2,
    APELLIDO VARCHAR2,
    CORREO VARCHAR2,
    TELEFONO VARCHAR2,
    REG_ACTIVO NUMBER, 
    ID_STORE NUMBER,
    ID_MANAGER NUMBER
)
IS
    MSJ NUMBER; 
BEGIN
    SP_INSERT_STAFFS(
        ID_STAFF,
        PRIM_NOMBRE,
        APELLIDO,
        CORREO,
        TELEFONO,
        REG_ACTIVO,
        ID_STORE,
        ID_MANAGER,
        MSJ
    );

    INSERT INTO BITACORAS (
        DESCRIPCION,
        FECHA_HORA,
        USUARIO,
        OPERACION
    )
    VALUES (
        'SE INSERTO UN REGISTRO EN LA TABLA STAFF',
        SYSTIMESTAMP,
        USER,
        'INSERT'
    );

    DBMS_OUTPUT.PUT_LINE('MSJ: ' || MSJ);
    IF (MSJ = 1) THEN
        COMMIT;
    ELSIF (MSJ = 2) THEN
        ROLLBACK;
    END IF;
END;


CREATE OR REPLACE PROCEDURE SP_INSERT_STAFFS(
    ID_STAFF NUMBER,
    PRIM_NOMBRE VARCHAR2,
    APELLIDO VARCHAR2,
    CORREO VARCHAR2,
    TELEFONO VARCHAR2,
    REG_ACTIVO NUMBER, 
    ID_STORE NUMBER,
    ID_MANAGER NUMBER,
    MSJ OUT NUMBER
)
IS

BEGIN
    INSERT INTO STAFFS VALUES (
        ID_STAFF,
        PRIM_NOMBRE,
        APELLIDO,
        CORREO,
        TELEFONO,
        REG_ACTIVO,
        ID_STORE,
        ID_MANAGER
    );
    MSJ := 1;

    EXCEPTION
        WHEN OTHERS THEN
        MSJ := 2;
END;

--EXECUTE
EXECUTE SP_VALORES_REG_STAFF(
    11,
    'GABRIEL',
    'ESCOBAR',
    'CORREO@UNAH.HN',
    '1234558',
    1,
    3,
    7
);