--- PROCEDIMIENTO QUE ALMACENA UN BRAND EN CASO DE NO EXISTIR REGISTRO DE EL ---

CREATE OR REPLACE PROCEDURE SP_INSERTA_PRODUCTO(
    NOMB_PROD VARCHAR2,
    ID_BRAND NUMBER,
    CAT_ID NUMBER, 
    ANIO_MODELO NUMBER,
    PRECIO NUMBER,
    NOMBRE_BRAND VARCHAR2,
    MSJ_ERROR OUT VARCHAR2,
    MSJ_EXITO OUT VARCHAR2
)
IS
    CANTIDAD_REGISTROS NUMBER;
    COD_BRAND NUMBER;
BEGIN
    SELECT COUNT(*) INTO CANTIDAD_REGISTROS FROM BRANDS WHERE BRAND_ID=ID_BRAND;

    IF(CANTIDAD_REGISTROS=1) THEN
        INSERT INTO PRODUCTS 
        (
            PRODUCT_NAME,
            BRAND_ID,
            CATEGORY_ID,
            MODEL_YEAR,
            LIST_PRICE
        )
        VALUES (
            NOMB_PROD,
            ID_BRAND,
            CAT_ID,
            ANIO_MODELO,
            PRECIO
        );

        COMMIT;
        MSJ_EXITO := 'LA INSERCION DEL PRODUCTO FUE EXITOSA';

    ELSE
        SP_INSERTA_BRAND(NOMBRE_BRAND, COD_BRAND);
        INSERT INTO PRODUCTS 
        (
            PRODUCT_NAME,
            BRAND_ID,
            CATEGORY_ID,
            MODEL_YEAR,
            LIST_PRICE
        )
        VALUES (
            NOMB_PROD,
            COD_BRAND,
            CAT_ID,
            ANIO_MODELO,
            PRECIO
        );
    END IF;
    

    EXCEPTION
        WHEN OTHERS THEN
            MSJ_ERROR:=SQLERRM;
END;



--- CREAR PROCEDIMIENTO PARA INSERTAR MARCA ---
CREATE SEQUENCE SQ_BRAND
START WITH 10
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TG_SQ_BRANDS
BEFORE INSERT ON BRANDS
FOR EACH ROW
DECLARE
BEGIN 
    :NEW.BRAND_ID:=SQ_BRAND.NEXTVAL;
END;

CREATE OR REPLACE PROCEDURE SP_INSERTA_BRAND
(
    NOMBRE_BRAND VARCHAR2,
    ID_BRAND OUT NUMBER
)
IS
BEGIN
    INSERT INTO BRANDS (BRAND_NAME)
    VALUES(NOMBRE_BRAND);

    SELECT BRAND_ID INTO ID_BRAND FROM BRANDS WHERE BRAND_NAME=NOMBRE_BRAND;

    COMMIT;
END;



--- PRUEBA DE INSERCION CON BRAND ID INEXISTENTE ---
DECLARE
    MSJ_ERROR VARCHAR2(500);
    MSJ_EXITO VARCHAR2(500);
BEGIN
    SP_INSERTA_PRODUCTO(
        'BICICLETA DE PRUEBA 2',
        30,
        4,
        2020,
        5345,
        'BRAND PRUEBA 2'
        MSJ_ERROR,
        MSJ_EXITO
    );
    DBMS_OUTPUT.PUT_LINE( MSJ_EXITO || ' ' || MSJ_ERROR );
END;
