-- CREAR UN SP QUE OBTENGA LA CANTIDAD TOTAL DE PRODUCTOS
CREATE OR REPLACE PROCEDURE  SP_CANT_PRODUCTOS
IS
    CANTIDAD NUMBER;
BEGIN
    SELECT COUNT(*) INTO CANTIDAD FROM PRODUCTS;
    DBMS_OUTPUT.PUT_LINE('LA CANTIDAD DE PRODUCTOS GUARDADOS ES: ' || CANTIDAD);
END;

EXECUTE SP_CANT_PRODUCTOS;

--! NO SE PUEDE USAR PROCEDIMIENTOS ALMACENADOS DENTRO DE CONSULTAS.